hw1
AnatoliyNik/courses-app pull request #1
Opened 2023-03-20 17:07 UTC by AnatoliyNik

2023-03-20 20:17 UTC, KitTheProgrammer requested changes

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		}
I understand what you tried to do here, but it is better to use regexp in this kind of situation and not use 2 values

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		setDuration(+target.value);
It is a bad habit to cast types like this, use `Number(<some string>)`. And I think that logical statement can be shortened as I commented higher

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		setAuthorList([...authorList]);
1. You can do it the short way as I wrote higher
2. more important that you are using 2 sources of truth. If you decided to use global context grab author list from there and don't create a copy for this component (related to lines 35 and 41)

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		setCourseAuthors([...courseAuthors]);
Never mutate state or context!

just use `[...courseAuthors, author]` here

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		setAuthorList(filtered);
`filtered` variable is redundant

2023-03-20 20:17 UTC, KitTheProgrammer commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +	};
Exactly the same here

2023-03-21 14:27 UTC, AnatoliyNik commented on src/components/CreateCourse/CreateCourse.jsx
> +		}
Если написать в одной строке value.length < minLength && !isShowError, то при изменении
isShowError в true, программа будет переходить в ветку else и там менять его на false при истинном условии value.length < minLength.
Переписал без else, чтоб лучше читалось:
               if (value.length < minLength && !isShowError) {
			setIsShowError(true);
		}

		if (value.length >= minLength && isShowError) {
			setIsShowError(false);
		}

2023-03-21 14:49 UTC, AnatoliyNik commented on src/components/CreateCourse/components/Authors/Authors.jsx
> +		setAuthorList([...authorList]);
Я делаю копию глобального массива, т.к. локальный массив изменяется при добавлении или удалении авторов курса

2023-03-21 17:10 UTC, KitTheProgrammer approved these changes
Great!
20

2023-03-21 17:15 UTC, merged